In [2]:
import implicit
import numpy as np
from scipy.sparse import csr_matrix

c:\Users\James\miniconda3\envs\cmu_10718\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
user_item_data = np.array(
    [
        [4, 0, 3],  # User 0's interactions
        [0, 2, 0],  # User 1's interactions
        [1, 0, 0],  # User 2's interactions
    ]
)
user_item_matrix = csr_matrix(user_item_data)
model = implicit.als.AlternatingLeastSquares(
    factors=20, regularization=0.1, iterations=20, random_state=42
)
model.fit(user_item_matrix)
print(model.user_factors.shape, model.item_factors.shape)
model.user_factors @ model.item_factors.T

100%|██████████| 20/20 [00:00<00:00, 2294.98it/s]

(3, 20) (3, 20)


array([[9.9007642e-01, 4.3813594e-05, 9.7189111e-01],
       [6.7100380e-05, 9.4881463e-01, 4.4013868e-05],
       [9.1090393e-01, 2.5472951e-05, 4.4911139e-02]], dtype=float32)

In [12]:
frozen_item_factors = model.item_factors.copy()

new_user_item_data = np.array([[5, 5, 5]])
new_user_item_matrix = csr_matrix(new_user_item_data)
model.partial_fit_users(userids=[3], user_items=new_user_item_matrix)
model.user_factors @ model.item_factors.T

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
